Content on the financials page under the pictures needs to be updated
international-child-art-foundation/icaf pull request #16
Opened 2023-06-23 08:44 UTC by adelSoltane

Fixes #15

2023-06-24 19:19 UTC, Andrew-Dame requested changes

2023-06-24 19:19 UTC, Andrew-Dame commented on about/financials.html
> +            <div class="sections">Download
Please change the names of the following classes to be singular rather than plural:

`section-titles`
`sections`

2023-06-24 19:19 UTC, Andrew-Dame commented on about/financials.html
> +            </div><br><br>
It's not great practice to use repeated`<br/>` to separate content. But this seems to be the convention. We need to  rework some of these CSS rules in the future as they could be less repetitive and more impactful.

2023-06-24 19:19 UTC, Andrew-Dame commented on about/financials.html
> +                <a href="/resource/image/about/financials/Code of Ethics_ICAF.pdf" class="pdf-link" target="_blank">Code of Ethics </a>as (pdfs)
Please add a period (for the sake of grammar)

`...as (pdfs).`

2023-06-26 03:35 UTC, adelSoltane commented on about/financials.html
> +            </div><br><br>
Thank you for pointing this out. I tried chaging it through the CSS but it didn't work.

2023-06-26 09:11 UTC, adelSoltane commented on about/financials.html
> +            </div><br><br>
Thank you for pointing this out. I changed it.

2023-06-27 00:43 UTC, Andrew-Dame requested changes

2023-06-27 00:43 UTC, Andrew-Dame commented on css/about/financials.scss
> +  .list-wrapper {
Please drop this rule since it doesn't offer any benefit at this time. It is redundant as `.content-wrapper .list-wrapper` applies to the relevant elements in the associated HTML.

2023-06-27 00:43 UTC, Andrew-Dame commented on css/about/financials.scss
> +    ul {
No benefit at this time, please remove.

2023-06-27 00:43 UTC, Andrew-Dame commented on css/about/financials.scss
> +    line-height: 100px;
Please revert this value back to `33px`.

2023-06-27 00:43 UTC, Andrew-Dame commented on css/about/financials.scss
> +  .section {
No benefit at this time, please remove.

2023-06-27 00:43 UTC, Andrew-Dame commented on about/financials.html
> +            <div class="section">Download
Please add `<br/><br/>` before this `div` element for now. Sorry if my last comment was confusing.

2023-06-27 00:43 UTC, Andrew-Dame commented on about/financials.html
> +            <div class="list-wrapper">
Please add `<br/><br/>` before this `div` element for now. Sorry if my last comment was confusing.

2023-06-29 01:39 UTC, Andrew-Dame approved these changes
This looks great, thanks for your work. Please remember to follow the [contributing guidelines ](https://github.com/international-child-art-foundation/icaf/blob/main/CONTRIBUTING.md) when submitting your PR.

2023-06-29 19:11 UTC, merged