fix: fill gap in childarts page carousel with new image (#14)
international-child-art-foundation/icaf pull request #19
Opened 2023-06-25 02:54 UTC by kojiro-soooo

2023-06-25 16:13 UTC, Andrew-Dame requested changes

2023-06-25 16:13 UTC, Andrew-Dame commented on js/json/childArtMagazineData.json
> +	{"name":"2023_q2", "coverImg":"/resource/image/mission/childart-magazine/2023_q2.jpg"},
Please change these filenames (and subsequent references) to be lowercase and use hyphens. Ex.

`2023-q2.jpg`

This is a widely used [convention](https://developers.google.com/style/filenames).

2023-06-26 01:03 UTC, kojiro-soooo commented on js/json/childArtMagazineData.json
> +	{"name":"2023_q2", "coverImg":"/resource/image/mission/childart-magazine/2023_q2.jpg"},
@Andrew-Dame Done. Thanks for the link!

2023-06-26 16:29 UTC, Andrew-Dame commented on js/json/childArtMagazineData.json
> +	{"name":"2023_q2", "coverImg":"/resource/image/mission/childart-magazine/2023_q2.jpg"},
Thanks for doing this! I realize this wasn't related to the issue.

2023-06-26 16:30 UTC, Andrew-Dame approved these changes

2023-06-26 17:52 UTC, merged