fix: update achievement links in impact page with valid resources
international-child-art-foundation/icaf pull request #20
Opened 2023-06-26 04:10 UTC by kojiro-soooo

Addresses https://github.com/international-child-art-foundation/icaf/issues/10

2023-06-27 00:53 UTC, Andrew-Dame requested changes

2023-06-27 00:53 UTC, Andrew-Dame commented on js/json/timelineData.json
> +    "imgLink": "https://icaf.org/resource/flipbooks/ThePowerOfWords/",
I don't believe the `https://icaf.org` prefix here is necessary...some of these resources are not checked in and just exist on the production file system due to memory concerns. Please remove for any affected links.

2023-06-27 00:53 UTC, Andrew-Dame commented on js/json/timelineData.json
> +    "imgLink": "/resource/image/impact/timeline/2022/Metaverse safety week.jpg",
Please update any resource _that you touched_ and _that are checked in_ (so hopefully only a few) to have a filename that is lowercase with a hyphen.

2023-06-27 00:53 UTC, Andrew-Dame commented on js/json/timelineData.json
> +    "description": "4th World Children’s Festival at the National Mall across the U.S. Capitol"
I think the grammatically correct think to do here is `fourth` instead of `4th`? Just a wild guess :)

2023-06-27 22:53 UTC, kojiro-soooo commented on js/json/timelineData.json
> +    "imgLink": "https://icaf.org/resource/flipbooks/ThePowerOfWords/",
Ah that makes sense, that's good to know for the future too.

2023-06-27 22:55 UTC, kojiro-soooo commented on js/json/timelineData.json
> +    "description": "4th World Children’s Festival at the National Mall across the U.S. Capitol"
Good catch, I also went ahead and fixed the same issue showing up in other parts of the timeline (e.g. 1st -> First)

2023-06-29 01:40 UTC, Andrew-Dame approved these changes

2023-06-29 02:36 UTC, merged